// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PintoresApp.Infrastructure.Persistence;

#nullable disable

namespace PintoresApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260922232549_AgregarMovimientoArtistico")]
    partial class AgregarMovimientoArtistico
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.20");

            modelBuilder.Entity("PintoresApp.Domain.Entities.MovimientoArtistico", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaisOrigen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MovimientosArtisticos", (string)null);
                });

            modelBuilder.Entity("PintoresApp.Domain.Entities.Pintor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MovimientoArtisticoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nacionalidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MovimientoArtisticoId");

                    b.ToTable("Pintores", (string)null);
                });

            modelBuilder.Entity("PintoresApp.Domain.Entities.Pintor", b =>
                {
                    b.HasOne("PintoresApp.Domain.Entities.MovimientoArtistico", "MovimientoArtistico")
                        .WithMany("Pintores")
                        .HasForeignKey("MovimientoArtisticoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MovimientoArtistico");
                });

            modelBuilder.Entity("PintoresApp.Domain.Entities.MovimientoArtistico", b =>
                {
                    b.Navigation("Pintores");
                });
#pragma warning restore 612, 618
        }
    }
}
